apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv0001
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain